replicaCount: 1

image:
  repository: signalen/frontend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/hsts-include-subdomains: "true"
    ingress.kubernetes.io/hsts-max-age: "315360000"
    ingress.kubernetes.io/hsts-preload: "true"
    ingress.kubernetes.io/ssl-redirect: "true"
  host: frontend.signals.local
  tls:
    - secretName: frontend-tls
      hosts:
        - frontend.signals.local

config:
  logoUrl: null
  logoHeight: 0
  sentry: null
  matamo: null
  language:
    footer1: "Hier komt een informatietekst"
    footer2: "die je zelf kan configureren."
  links:
    home: https://frontend.signals.local
    privacy: https://privacy.signals.local
  theme: {}
  map:
    tiles:
      args:
        - "https://{s}.data.amsterdam.nl/topo_rd/{z}/{x}/{y}.png"
      options:
        subdomains: ["t1", "t2", "t3", "t4"]
        tms: true
        attribution: "Kaartgegevens CC-BY-4.0 Gemeente Amsterdam"
    options:
      maxBounds:
        - [52.25168, 4.64034]
        - [52.50536, 5.10737]
      center: [52.3731081, 4.8932945]
      zoom: 10
  ROOT: https://api.signals.local/
  AUTH_ROOT: https://auth.signals.local/
  API_ROOT_MAPSERVER: https://map.data.amsterdam.nl/
  USERS_ENDPOINT: https://api.signals.local/signals/v1/private/users/
  ROLES_ENDPOINT: https://api.signals.local/signals/v1/private/roles/
  PERMISSIONS_ENDPOINT: https://api.signals.local/signals/v1/private/permissions/
  SEARCH_ENDPOINT: https://api.signals.local/signals/v1/private/search
  PREDICTION_ENDPOINT: https://api.signals.local/signals/category/prediction
  INCIDENT_PUBLIC_ENDPOINT: https://api.signals.local/signals/v1/public/signals/
  INCIDENT_PRIVATE_ENDPOINT: https://api.signals.local/signals/v1/private/signals/
  INCIDENTS_ENDPOINT: https://api.signals.local/signals/v1/private/signals/
  GEOGRAPHY_ENDPOINT: https://api.signals.local/signals/v1/private/signals/geography
  PRIORITY_ENDPOINT: https://api.signals.local/signals/auth/priority/
  FEEDBACK_STANDARD_ANSWERS_ENDPOINT: https://api.signals.local/signals/v1/public/feedback/standard_answers/
  FEEDBACK_FORMS_ENDPOINT: https://api.signals.local/signals/v1/public/feedback/forms/
  AUTH_ME_ENDPOINT: https://api.signals.local/signals/v1/private/me/
  CATEGORIES_PRIVATE_ENDPOINT: https://api.signals.local/signals/v1/private/categories/
  CATEGORIES_ENDPOINT: https://api.signals.local/signals/v1/public/terms/categories/
  TERMS_ENDPOINT: https://api.signals.local/signals/v1/private/terms/categories/
  IMAGE_ENDPOINT: https://api.signals.local/signals/signal/image/
  FILTERS_ENDPOINT: https://api.signals.local/signals/v1/private/me/filters/
  DEPARTMENTS_ENDPOINT: https://api.signals.local/signals/v1/private/departments/
  DASHBOARD_ENDPOINT: https://api.signals.local/signals/experimental/dashboards/1
  OVL_KLOKKEN_LAYER: https://map.data.amsterdam.nl/maps/openbare_verlichting?REQUEST=GetFeature&SERVICE=wfs&OUTPUTFORMAT=application/json;%20subtype=geojson;%20charset=utf-8&Typename=Klokken&version=1.1.0&srsname=urn:ogc:def:crs:EPSG::4326
  OVL_VERLICHTING_LAYER: https://map.data.amsterdam.nl/maps/openbare_verlichting?REQUEST=GetFeature&SERVICE=wfs&OUTPUTFORMAT=application/json;%20subtype=geojson;%20charset=utf-8&Typename=Verlichting&version=1.1.0&srsname=urn:ogc:def:crs:EPSG::4326
