apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "signals-backend.migrate" . }}-{{ randAlphaNum 5 | lower }}
  labels:
    {{- include "signals-backend.labels" . | nindent 4 }}
spec:
  backoffLimit: 6
  ttlSecondsAfterFinished: 60
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/app/manage.py"]
          args: ["migrate"]
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "signals-backend.fullname" . }}
                  key: secret-key
            - name: DATABASE_HOST_OVERRIDE
              value: {{ .Values.settings.database.host }}
            - name: DATABASE_PORT_OVERRIDE
              value: {{ .Values.settings.database.port | quote }}
            - name: DATABASE_USER
              value: {{ .Values.settings.database.username }}
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "signals-backend.fullname" . }}
                  key: database-password
            - name: DATABASE_NAME
              value: {{ .Values.settings.database.name }}