apiVersion: v1
kind: Secret
metadata:
  name: {{ template "signals-backend.fullname" . }}
  labels:
    {{- include "signals-backend.labels" . | nindent 4 }}
type: Opaque
data:
  secret-key: {{ randAlphaNum 10 | b64enc }}
  database-password: {{ .Values.database.password | b64enc }}
  rabbitmq-password: {{ .Values.celery.rabbitmq.password | b64enc }}
  smtp-password: {{ .Values.smtp.password | quote | b64enc }}
{{- if .Values.sigmax.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "signals-backend.fullname" . }}-sigmax
  labels:
    {{- include "signals-backend.labels" . | nindent 4 }}
type: Opaque
data:
  auth-token: {{ .Values.sigmax.authToken | b64enc }}
{{- end }}
