replicaCount: 1

image:
  repository: signalen/frontend
  tag: latest
  pullPolicy: IfNotPresent

podAnnotations: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
  host: frontend.signals.local
  tls:
    - secretName: frontend-tls
      hosts:
        - frontend.signals.local

config: {}
