tags:
  postgresql: true
  rabbitmq: true
  elasticsearch: true

replicaCount: 1
workerReplicaCount: 1

deploymentStrategy: Recreate

image:
  repository: signalen/backend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/hsts-include-subdomains: "true"
    ingress.kubernetes.io/hsts-max-age: "315360000"
    ingress.kubernetes.io/hsts-preload: "true"
    ingress.kubernetes.io/ssl-redirect: "true"
  host: api.signals.local
  tls:
    - secretName: backend-tls
      hosts:
        - api.signals.local

persistence:
  enabled: true
  size: 1Gi
  existingClaim: null

settings:
  allowedHosts: "*"
  defaultPdokMunicipalities: ""
  defaultMapTileServer: ""
  pubJwks: ""
  jwksUrl: ""
  userIdField: "sub"

  organizationName: "Signalen"
  defaultFromEmail: "webmaster@localhost"

  apiTransformSourceBasedOnReporterSource: "Internal"
  apiTransformSourceBasedOnReporterDomainExtensions: "@localhost"
  apiTransformSourceBasedOnReporterExceptions: "ignore@localhost"

  apiPdfLogoStaticFile: api/logo-gemeente-amsterdam.svg

  database:
    host: signals-backend-postgresql
    port: 5432
    username: signals
    password: signals
    name: signals

  rabbitmq:
    host: signals-backend-rabbitmq
    username: signals
    password: signals
    vhost: ""

  elasticsearch:
    host: elasticsearch-master:9200 # first part corresponds with elasticsearch.clusterName
    index: signals

  email:
    hostname: mailhog
    port: 25
    username: ""
    password: ""
    useTLS: false
    useSSL: false

  datapuntApiUrl: https://api.data.amsterdam.nl/

  classificationEndpoint: https://api.data.amsterdam.nl/signals_mltool

  sigmax:
    enabled: false
    serverUrl: http://sigmax.sigmax
    authToken: insecure

#########################
## PostgreSQL subchart ##
#########################
postgresql:
  image:
    repository: amsterdam/postgres11
    tag: latest

  persistence:
    enabled: true
    size: 1Gi
    existingClaim: null

  postgresqlDatabase: signals
  postgresqlUsername: signals
  postgresqlPassword: signals

#######################
## RabbitMQ subchart ##
#######################
rabbitmq:
  image:
    tag: "3.8"

  rabbitmq:
    username: signals
    password: signals

  persistence:
    enabled: true
    size: 1Gi
    existingClaim: null

############################
## Elasticsearch subchart ##
############################
elasticsearch:
  clusterName: elasticsearch

  replicas: 1
  minimumMasterNodes: 1
  maxUnavailable: false
  clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"

  esJavaOpts: "-Xmx512m -Xms512m"

  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "500m"
      memory: "1Gi"
