apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "signals-api.celery-beat" . }}
  labels:
    {{- include "signals-api.labels" . | nindent 4 }}
    component: cellery-beat
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      {{- include "signals-api.selectorLabels" . | nindent 6 }}
      component: celery-beat
  template:
    metadata:
      labels:
        {{- include "signals-api.labels" . | nindent 8 }}
        component: celery-beat
    spec:
      containers:
        - name: celery-beat
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/local/bin/celery"]
          args: ["beat", "--app", "signals", "--loglevel", "WARNING"]
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: signals.settings.production
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "signals-api.fullname" . }}
                  key: secret-key

            - name: DATABASE_HOST_OVERRIDE
              value: {{ .Values.database.hostname }}
            - name: DATABASE_PORT_OVERRIDE
              value: "5432"
            - name: DATABASE_NAME
              value: {{ .Values.database.databaseName }}
            - name: DATABASE_USER
              value: {{ .Values.database.username }}
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "signals-api.fullname" . }}
                  key: database-password

            - name: RABBITMQ_HOST
              value: {{ .Values.celery.rabbitmq.hostname }}
            - name: RABBITMQ_VHOST
              value: ""
            - name: RABBITMQ_USER
              value: {{ .Values.celery.rabbitmq.username }}
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "signals-api.fullname" . }}
                  key: rabbitmq-password
