apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "signals-api.fullname" . }}
  labels:
    {{- include "signals-api.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
