apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "signals-backend.celery-worker" . }}
  labels:
    {{- include "signals-backend.labels" . | nindent 4 }}
    component: cellery-worker
spec:
  replicas: {{ .Values.workerReplicaCount }}
  selector:
    matchLabels:
      {{- include "signals-backend.selectorLabels" . | nindent 6 }}
      component: celery-worker
  strategy:
    type: {{ .Values.deploymentStrategy }}
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
        {{- include "signals-backend.labels" . | nindent 8 }}
        component: celery-worker
    spec:
      containers:
        - name: celery-worker
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/local/bin/celery"]
          args:
            - 'worker'
            - '--app=signals'
            - '--loglevel=WARNING'
            - '--concurrency={{ .Values.celery.concurrency }}'
          envFrom:
            - configMapRef:
                name: {{ template "signals-backend.fullname" . }}
            - secretRef:
                name: {{ if .Values.existingSecret }}{{ .Values.existingSecret }}{{ else }}{{ template "signals-backend.fullname" . }}{{ end }}
          volumeMounts:
            - name: dwh-media
              mountPath: /dwh_media
{{- if ne (len .Values.extraVolumeMounts) 0 }}
{{ toYaml .Values.extraVolumeMounts | indent 12 }}
{{- end }}
      volumes:
        - name: dwh-media
        {{- if .Values.persistence.datawarehouse.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.datawarehouse.existingClaim }}{{ .Values.persistence.datawarehouse.existingClaim }}{{ else }}{{ template "signals-backend.fullname" . }}-datawarehouse{{ end }}
        {{- else }}
          emptyDir: {}
        {{- end }}
{{- if ne (len .Values.extraVolumes) 0 }}
{{ toYaml .Values.extraVolumes | indent 8 }}
{{- end }}
