{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "signals-backend.fullname" . }}
  labels:
    {{- include "signals-backend.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_PASSWORD: {{ .Values.settings.database.password | b64enc | quote }}
  EMAIL_HOST_PASSWORD: {{ .Values.settings.email.password | b64enc | quote }}
  RABBITMQ_PASSWORD: {{ .Values.settings.rabbitmq.password | b64enc | quote }}
  SECRET_KEY: {{ .Values.settings.secretKey | b64enc | quote }}
  FLOWER_BASIC_AUTH: {{ .Values.flower.basicAuth | b64enc | quote }}
  {{- if .Values.settings.sigmax.enabled }}
  SIGMAX_AUTH_TOKEN: {{ .Values.settings.sigmax.authToken | b64enc | quote }}
  {{- end }}
{{- end }}
