replicaCount: 1

image:
  repository: registry.gitlab.com/commonground/signals/lightidp
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  class: traefik
  host: idp.signals.local

callbacks:
  - https://auth.signals.local

jwt:
  refreshSecret: aMCc9kXFSimVaLFxIb83
  lifetime: 30

createDemoAccount: true
demoAccount:
  emailAddress: admin@signals.local
  passwordHash: pbkdf2_sha256$30000$fN7ya-6Hu4Xwt2p8$Ti7h47AyNYcX4Ttf4wlgX09vcJc/kPaMSgBMTn3NQ7Q=  # querty123

###########################
## PostgreSQL (subchart) ##
###########################
postgresql:
  persistence:
    size: 1Gi

  postgresqlDatabase: idp
  postgresqlUsername: idp
  postgresqlPassword: idp
