apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "signals-frontend.fullname" . }}
  labels:
    {{- include "signals-frontend.labels" . | nindent 4 }}
data:
  environment.conf.json: {{ .Values.config | toJson | quote }}
