apiVersion: v2
name: backend
description: The API for the Signals application
type: application
version: 5.0.0
appVersion: 2.19.0

dependencies:
  - name: postgresql
    version: ~11.9.0
    repository: https://charts.bitnami.com/bitnami
    tags:
      - postgresql
  - name: rabbitmq
    version: ~11.16.0
    repository: https://charts.bitnami.com/bitnami
    tags:
      - rabbitmq
  - name: elasticsearch
    version: ~7.17.0
    repository: https://helm.elastic.co
    tags:
      - elasticsearch
