apiVersion: v2
name: backend
description: The API for the Signals application
type: application
version: 4.4.1
appVersion: 2.7.2

dependencies:
  - name: postgresql
    version: ~11.6.12
    repository: https://charts.bitnami.com/bitnami
    tags:
      - postgresql
  - name: rabbitmq
    version: ~9.1.4
    repository: https://charts.bitnami.com/bitnami
    tags:
      - rabbitmq
  - name: elasticsearch
    version: ~6.8.0
    repository: https://helm.elastic.co
    tags:
      - elasticsearch
