apiVersion: v1
kind: Service
metadata:
  name: {{ template "authz-admin.fullname" . }}
  labels:
    {{- include "authz-admin.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "authz-admin.labels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http
