apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "signals-backend.celery-worker" . }}
  labels:
    {{- include "signals-backend.labels" . | nindent 4 }}
    component: cellery-worker
spec:
  replicas: {{ .Values.workerReplicaCount }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      {{- include "signals-backend.selectorLabels" . | nindent 6 }}
      component: celery-worker
  strategy:
    type: {{ .Values.deploymentStrategy }}
  template:
    metadata:
      labels:
        {{- include "signals-backend.labels" . | nindent 8 }}
        component: celery-worker
    spec:
      containers:
        - name: celery-worker
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/local/bin/celery"]
          args: ["worker", "--app", "signals", "--loglevel", "WARNING"]
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: signals.settings.production
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "signals-backend.fullname" . }}
                  key: secret-key
            - name: DATABASE_HOST_OVERRIDE
              value: {{ .Values.settings.database.host }}
            - name: DATABASE_PORT_OVERRIDE
              value: {{ .Values.settings.database.port | quote }}
            - name: DATABASE_USER
              value: {{ .Values.settings.database.username }}
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "signals-backend.fullname" . }}
                  key: database-password
            - name: DATABASE_NAME
              value: {{ .Values.settings.database.name }}
            - name: RABBITMQ_HOST
              value: {{ .Values.settings.rabbitmq.host }}
            - name: RABBITMQ_USER
              value: {{ .Values.settings.rabbitmq.username }}
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "signals-backend.fullname" . }}
                  key: rabbitmq-password
            - name: RABBITMQ_VHOST
              value: {{ .Values.settings.rabbitmq.vhost }}
            - name: EMAIL_HOST
              value: {{ .Values.settings.email.hostname }}
            - name: EMAIL_PORT
              value: {{ .Values.settings.email.port | quote }}
            - name: EMAIL_HOST_USER
              value: {{ .Values.settings.email.username }}
            - name: EMAIL_HOST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "signals-backend.fullname" . }}
                  key: email-password
            - name: EMAIL_USE_TLS
              value: "{{ if .Values.settings.email.useTLS }}True{{ end }}"
            - name: EMAIL_USE_SSL
              value: "{{ if .Values.settings.email.useSSL }}True{{ end }}"
            {{- if .Values.settings.sigmax.enabled }}
            - name: SIGMAX_SERVER
              value: {{ .Values.settings.sigmax.serverUrl }}
            - name: SIGMAX_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ template "signals-backend.fullname" . }}-sigmax
                  key: auth-token
            {{- end }}
            - name: ELASTICSEARCH_HOST
              value: {{ .Values.settings.elasticsearch.host }}
            - name: ELASTICSEARCH_INDEX
              value: {{ .Values.settings.elasticsearch.index }}
