apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "signals-backend.migrate" . }}-{{ randAlphaNum 5 | lower }}
  labels:
    {{- include "signals-backend.labels" . | nindent 4 }}
spec:
  backoffLimit: 6
  ttlSecondsAfterFinished: 60
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/app/manage.py"]
          args: ["migrate"]
          envFrom:
            - secretRef:
                name: {{ template "signals-backend.fullname" . }}
