apiVersion: v1
kind: Secret
metadata:
  name: {{ template "signals-backend.fullname" . }}
  labels:
    {{- include "signals-backend.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
type: Opaque
data:
  ALLOWED_HOSTS: {{ .Values.settings.allowedHosts | b64enc }}
  API_PDF_LOGO_STATIC_FILE: {{ .Values.settings.apiPdfLogoStaticFile | b64enc }}
  API_TRANSFORM_SOURCE_BASED_ON_REPORTER_DOMAIN_EXTENSIONS: {{ .Values.settings.apiTransformSourceBasedOnReporterDomainExtensions | b64enc }}
  API_TRANSFORM_SOURCE_BASED_ON_REPORTER_EXCEPTIONS: {{ .Values.settings.apiTransformSourceBasedOnReporterExceptions | b64enc }}
  API_TRANSFORM_SOURCE_BASED_ON_REPORTER_SOURCE: {{ .Values.settings.apiTransformSourceBasedOnReporterSource | b64enc }}
  DATABASE_HOST_OVERRIDE: {{ .Values.settings.database.host | b64enc }}
  DATABASE_PORT_OVERRIDE: {{ .Values.settings.database.port | toString | b64enc }}
  DATABASE_USER: {{ .Values.settings.database.username | b64enc }}
  DATABASE_PASSWORD: {{ .Values.settings.database.password | b64enc }}
  DATABASE_NAME: {{ .Values.settings.database.name | b64enc }}
  DATAPUNT_API_URL: {{ .Values.settings.datapuntApiUrl | b64enc }}
  DEFAULT_FROM_EMAIL: {{ .Values.settings.defaultFromEmail | b64enc }}
  DEFAULT_MAP_TILE_SERVER: {{ .Values.settings.defaultMapTileServer | b64enc }}
  DEFAULT_PDOK_MUNICIPALITIES: {{ .Values.settings.defaultPdokMunicipalities | b64enc }}
  DWH_MEDIA_ROOT: {{ "/dwh_media" | b64enc }}
  DJANGO_LOG_LEVEL: {{ "error" | b64enc }}
  DJANGO_SETTINGS_MODULE: {{ "signals.settings.production" | b64enc }}
  EMAIL_HOST: {{ .Values.settings.email.hostname | b64enc }}
  EMAIL_PORT: {{ .Values.settings.email.port | toString | b64enc }}
  EMAIL_HOST_USER: {{ .Values.settings.email.username | toString | b64enc | quote }}
  EMAIL_HOST_PASSWORD: {{ .Values.settings.email.password | toString | b64enc | quote }}
  EMAIL_USE_TLS: {{ if .Values.settings.email.useTLS }}{{ "True" | b64enc | quote }}{{ else }}{{ "False" | b64enc | quote }}{{ end }}
  EMAIL_USE_SSL: {{ if .Values.settings.email.useSSL }}{{ "True" | b64enc | quote }}{{ else }}{{ "False" | b64enc | quote }}{{ end }}
  ELASTICSEARCH_HOST: {{ .Values.settings.elasticsearch.host | b64enc }}
  ELASTICSEARCH_INDEX: {{ .Values.settings.elasticsearch.index | b64enc }}
  JWKS_URL: {{ .Values.settings.jwksUrl | toString | b64enc | quote }}
  ORGANIZATION_NAME: {{ .Values.settings.organizationName | b64enc }}
  PUB_JWKS: {{ .Values.settings.pubJwks | toString | b64enc | quote }}
  RABBITMQ_HOST: {{ .Values.settings.rabbitmq.host | b64enc }}
  RABBITMQ_USER: {{ .Values.settings.rabbitmq.username | b64enc }}
  RABBITMQ_PASSWORD: {{ .Values.settings.rabbitmq.password | b64enc }}
  RABBITMQ_VHOST: {{ .Values.settings.rabbitmq.vhost | toString | b64enc | quote }}
  SECRET_KEY: {{ randAlphaNum 10 | b64enc }}
  {{- if .Values.settings.sigmax.enabled }}
  SIGMAX_SERVER: {{ .Values.settings.sigmax.serverUrl | b64enc }}
  SIGMAX_AUTH_TOKEN: {{ .Values.settings.sigmax.authToken | b64enc }}
  {{- end }}
  SIGNALS_ML_TOOL_ENDPOINT: {{ .Values.settings.classificationEndpoint | b64enc }}
  USER_ID_FIELDS: {{ .Values.settings.userIdField | b64enc }}
