apiVersion: v1
kind: Secret
metadata:
  name: {{ template "idp.fullname" . }}
  labels:
    {{- include "idp.labels" . | nindent 4 }}
type: Opaque
data:
  postgresql-password: {{ .Values.postgresql.postgresqlPassword | b64enc }}
  jwt-refresh-secret: {{ .Values.jwt.refreshSecret | b64enc }}
