apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "signals-classification.fullname" . }}
  labels:
    {{- include "signals-classification.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "signals-classification.fullname" . }}
              servicePort: http
